//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FCC.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_MESSAGE_NEWDOCUMENT         101
#define IDS_INDICATOR_MESSAGE           102
#define IDD_NEWDLG                      103
#define IDS_INDICATOR_RUNNING           103
#define IDS_INDICATOR_WARNING           104
#define IDS_MESSAGE_EDITDOCUMENT        105
#define IDS_MESSAGE_WELCOME             106
#define IDS_MESSAGE_SAVE                107
#define IDS_MESSAGE_RESTORE             108
#define IDD_FPDLG                       109
#define IDS_MESSAGE_FATALFILEREADING    109
#define IDS_MESSAGE_FPREADINGSUCC       110
#define IDD_TRAINDLG                    111
#define IDS_MESSAGE_TRAINING            111
#define IDS_MESSAGE_TRAINFINISHED       112
#define IDS_MESSAGE_NOMEMORY            113
#define IDS_MESSAGE_SMALLZOOMRATIO      114
#define IDS_MESSAGE_SELECTCLASSIFIER    115
#define IDD_FINDDIALOG                  116
#define IDS_TAG_PROJECT_TITLE           116
#define IDD_PREDDLG                     117
#define IDS_TAG_FP_TITLE                117
#define IDD_EXPDLG                      118
#define IDS_TAG_TRAIN_TITLE             118
#define IDS_TAG_PREDICT_TITLE           119
#define IDR_MAINFRAME                   128
#define IDR_FCCTYPE                     129
#define IDB_MESSAGE                     130
#define IDB_WARNING                     131
#define IDB_RUNNING                     132
#define IDD_DISPSETTING                 133
#define IDR_FCCVIEWMENU                 134
#define IDB_LEFTMOST                    136
#define IDB_LEFT                        137
#define IDB_RIGHT                       138
#define IDB_RIGHTMOST                   139
#define IDB_BITMAP1                     140
#define IDB_DROPDOWN                    140
#define IDB_SCROLLUP                    141
#define IDB_BITMAP2                     142
#define IDB_CHECK                       142
#define IDB_BITMAP3                     147
#define IDB_BITMAP4                     148
#define IDC_ASCEND                      154
#define IDC_DESCEND                     155
#define IDB_YELLOWTAG                   156
#define IDB_GREENTAG                    157
#define IDB_REDTAG                      158
#define IDI_PROJECT                     162
#define IDI_FP                          163
#define IDI_TRAIN                       164
#define IDI_PREDICT                     165
#define IDI_HELP                        166
#define IDS_TAG_PROJECT_INFO            216
#define IDS_TAG_FP_INFO                 217
#define IDS_TAG_TRAIN_INFO              218
#define IDS_TAG_PREDICT_INFO            219
#define IDC_EDIT2                       1001
#define IDC_EDIT3                       1002
#define IDC_EDIT4                       1003
#define IDC_EDIT1                       1004
#define IDC_BUTTON1                     1005
#define IDC_RADIO1                      1006
#define IDC_RADIO2                      1007
#define IDC_RADIO3                      1008
#define IDC_CHECK1                      1009
#define IDC_CHECK2                      1010
#define IDC_COMBO1                      1011
#define IDC_COMBO2                      1012
#define IDC_COMBO3                      1013
#define IDC_COMBO4                      1014
#define IDC_SPIN1                       1016
#define IDC_SPIN2                       1017
#define IDC_COMBO5                      1018
#define IDC_COMBO6                      1019
#define IDC_BUTTON2                     1020
#define IDC_FINDNEXT                    1020
#define IDC_FINDPREV                    1021
#define IDC_BUTTON3                     1022
#define ID_VIEW_VIEWFINGERPRINT         32771
#define ID_ADABOOST_MODELTRAINING       32772
#define ID_ADABOOST_PREDICTING          32773
#define ID_EDIT_EDITPROJECTTITLE        32774
#define ID_Menu                         32775
#define ID_FILE_LOADFINGERPRINTS        32776
#define ID_VIEW_FITTOWINDOWSIZE         32777
#define ID_VIEW_VERTICALZOOM            32778
#define ID_VIEW_HORIZONALZOOM           32779
#define ID_VIEW_VERTICALZOOM32780       32780
#define ID_VIEW_HORIZONALZOOM32781      32781
#define ID_VIEW_DISPLAYOPTION           32782
#define ID_VIEW_VERTICALZOOMIN          32784
#define ID_VIEW_HORIZONALZOOMIN         32785
#define ID_VIEW_VERTICALZOOMOUT         32786
#define ID_VIEW_HORIZONALZOOMOUT        32787
#define ID_VIEW_SHOWCOORDINATES         32794
#define ID_VIEW_PREDICTION              32795
#define ID_VIEW_TRAININGERROR           32796
#define ID_EDIT_FIND32797               32797
#define ID_EDIT_STOPTRAINING            32800
#define ID_EDIT_EXPORT                  32801
#define ID_EDIT_SELECTALL               32802
#define ID_HELP_CONTENTS                32803
#define ID_CPREDVIEW_INVERSESELECTION   32804
#define ID_VIEW_STARTUPPAGE             32805
#define ID_EDIT_SHELL                   32813
#define ID_Menu32814                    32814
#define ID_EditParameterOpt             32815
#define IDS_MESSAGE_FAILOPENFILE        61446
#define IDS_MESSAGE_MEMORY              61447
#define IDS_MESSAGE_INCORRECTFORMAT     61448
#define IDS_MESSAGE_INCONSISTENTLENGTH  61449
#define IDS_MESSAGE_STARTPRINT          61450
#define IDS_MESSAGE_ENDPRINT            61451
#define IDS_MESSAGE_CUSTOM              61452
#define IDS_MESSAGE_NOTRAININGDATA      61453
#define IDS_MESSAGE_STOPTRAINING        61454
#define IDS_MESSAGE_EXPORTMODEL         61455
#define IDS_MESSAGE_EXPORTPREDICTION    61456
#define IDS_MESSAGE_COPY                61457
#define IDS_MESSAGE_NOITEMSELECTED      61458
#define IDS_MESSAGE_PASTE               61459
#define IDS_MESSAGE_FINDCOMPOUND        61460
#define IDS_MESSAGE_NUMITEMSELECTED     61461
#define IDS_MESSAGE_MAKEPREDICTION      61462
#define IDS_MESSAGE_FITWINDOW           61463
#define IDS_MESSAGE_OPTIMALSTEP         61464

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         32816
#define _APS_NEXT_CONTROL_VALUE         1023
#define _APS_NEXT_SYMED_VALUE           119
#endif
#endif
